/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspaceIdRouteImport } from './routes/_app.$workspaceId'
import { Route as AppWorkspaceIdUsageRouteImport } from './routes/_app.$workspaceId.usage'
import { Route as AppWorkspaceIdTasksRouteImport } from './routes/_app.$workspaceId.tasks'
import { Route as AppWorkspaceIdSettingsRouteImport } from './routes/_app.$workspaceId.settings'
import { Route as AppWorkspaceIdDashboardRouteImport } from './routes/_app.$workspaceId.dashboard'
import { Route as AppWorkspaceIdAgentsRouteImport } from './routes/_app.$workspaceId.agents'
import { Route as AppWorkspaceIdSettingsIndexRouteImport } from './routes/_app.$workspaceId.settings.index'
import { Route as AppWorkspaceIdSettingsSecurityRouteImport } from './routes/_app.$workspaceId.settings.security'
import { Route as AppWorkspaceIdSettingsNotificationsRouteImport } from './routes/_app.$workspaceId.settings.notifications'
import { Route as AppWorkspaceIdSettingsMembersRouteImport } from './routes/_app.$workspaceId.settings.members'
import { Route as AppWorkspaceIdSettingsGeneralRouteImport } from './routes/_app.$workspaceId.settings.general'
import { Route as AppWorkspaceIdSettingsBillingRouteImport } from './routes/_app.$workspaceId.settings.billing'
import { Route as AppWorkspaceIdAgentsCreateRouteImport } from './routes/_app.$workspaceId.agents.create'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceIdRoute = AppWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceIdUsageRoute = AppWorkspaceIdUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppWorkspaceIdRoute,
} as any)
const AppWorkspaceIdTasksRoute = AppWorkspaceIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppWorkspaceIdRoute,
} as any)
const AppWorkspaceIdSettingsRoute = AppWorkspaceIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppWorkspaceIdRoute,
} as any)
const AppWorkspaceIdDashboardRoute = AppWorkspaceIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppWorkspaceIdRoute,
} as any)
const AppWorkspaceIdAgentsRoute = AppWorkspaceIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppWorkspaceIdRoute,
} as any)
const AppWorkspaceIdSettingsIndexRoute =
  AppWorkspaceIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceIdSettingsRoute,
  } as any)
const AppWorkspaceIdSettingsSecurityRoute =
  AppWorkspaceIdSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AppWorkspaceIdSettingsRoute,
  } as any)
const AppWorkspaceIdSettingsNotificationsRoute =
  AppWorkspaceIdSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppWorkspaceIdSettingsRoute,
  } as any)
const AppWorkspaceIdSettingsMembersRoute =
  AppWorkspaceIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppWorkspaceIdSettingsRoute,
  } as any)
const AppWorkspaceIdSettingsGeneralRoute =
  AppWorkspaceIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AppWorkspaceIdSettingsRoute,
  } as any)
const AppWorkspaceIdSettingsBillingRoute =
  AppWorkspaceIdSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppWorkspaceIdSettingsRoute,
  } as any)
const AppWorkspaceIdAgentsCreateRoute =
  AppWorkspaceIdAgentsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppWorkspaceIdAgentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/usage': typeof UsageRoute
  '/$workspaceId': typeof AppWorkspaceIdRouteWithChildren
  '/$workspaceId/agents': typeof AppWorkspaceIdAgentsRouteWithChildren
  '/$workspaceId/dashboard': typeof AppWorkspaceIdDashboardRoute
  '/$workspaceId/settings': typeof AppWorkspaceIdSettingsRouteWithChildren
  '/$workspaceId/tasks': typeof AppWorkspaceIdTasksRoute
  '/$workspaceId/usage': typeof AppWorkspaceIdUsageRoute
  '/$workspaceId/agents/create': typeof AppWorkspaceIdAgentsCreateRoute
  '/$workspaceId/settings/billing': typeof AppWorkspaceIdSettingsBillingRoute
  '/$workspaceId/settings/general': typeof AppWorkspaceIdSettingsGeneralRoute
  '/$workspaceId/settings/members': typeof AppWorkspaceIdSettingsMembersRoute
  '/$workspaceId/settings/notifications': typeof AppWorkspaceIdSettingsNotificationsRoute
  '/$workspaceId/settings/security': typeof AppWorkspaceIdSettingsSecurityRoute
  '/$workspaceId/settings/': typeof AppWorkspaceIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/usage': typeof UsageRoute
  '/$workspaceId': typeof AppWorkspaceIdRouteWithChildren
  '/$workspaceId/agents': typeof AppWorkspaceIdAgentsRouteWithChildren
  '/$workspaceId/dashboard': typeof AppWorkspaceIdDashboardRoute
  '/$workspaceId/tasks': typeof AppWorkspaceIdTasksRoute
  '/$workspaceId/usage': typeof AppWorkspaceIdUsageRoute
  '/$workspaceId/agents/create': typeof AppWorkspaceIdAgentsCreateRoute
  '/$workspaceId/settings/billing': typeof AppWorkspaceIdSettingsBillingRoute
  '/$workspaceId/settings/general': typeof AppWorkspaceIdSettingsGeneralRoute
  '/$workspaceId/settings/members': typeof AppWorkspaceIdSettingsMembersRoute
  '/$workspaceId/settings/notifications': typeof AppWorkspaceIdSettingsNotificationsRoute
  '/$workspaceId/settings/security': typeof AppWorkspaceIdSettingsSecurityRoute
  '/$workspaceId/settings': typeof AppWorkspaceIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/usage': typeof UsageRoute
  '/_app/$workspaceId': typeof AppWorkspaceIdRouteWithChildren
  '/_app/$workspaceId/agents': typeof AppWorkspaceIdAgentsRouteWithChildren
  '/_app/$workspaceId/dashboard': typeof AppWorkspaceIdDashboardRoute
  '/_app/$workspaceId/settings': typeof AppWorkspaceIdSettingsRouteWithChildren
  '/_app/$workspaceId/tasks': typeof AppWorkspaceIdTasksRoute
  '/_app/$workspaceId/usage': typeof AppWorkspaceIdUsageRoute
  '/_app/$workspaceId/agents/create': typeof AppWorkspaceIdAgentsCreateRoute
  '/_app/$workspaceId/settings/billing': typeof AppWorkspaceIdSettingsBillingRoute
  '/_app/$workspaceId/settings/general': typeof AppWorkspaceIdSettingsGeneralRoute
  '/_app/$workspaceId/settings/members': typeof AppWorkspaceIdSettingsMembersRoute
  '/_app/$workspaceId/settings/notifications': typeof AppWorkspaceIdSettingsNotificationsRoute
  '/_app/$workspaceId/settings/security': typeof AppWorkspaceIdSettingsSecurityRoute
  '/_app/$workspaceId/settings/': typeof AppWorkspaceIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/usage'
    | '/$workspaceId'
    | '/$workspaceId/agents'
    | '/$workspaceId/dashboard'
    | '/$workspaceId/settings'
    | '/$workspaceId/tasks'
    | '/$workspaceId/usage'
    | '/$workspaceId/agents/create'
    | '/$workspaceId/settings/billing'
    | '/$workspaceId/settings/general'
    | '/$workspaceId/settings/members'
    | '/$workspaceId/settings/notifications'
    | '/$workspaceId/settings/security'
    | '/$workspaceId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/usage'
    | '/$workspaceId'
    | '/$workspaceId/agents'
    | '/$workspaceId/dashboard'
    | '/$workspaceId/tasks'
    | '/$workspaceId/usage'
    | '/$workspaceId/agents/create'
    | '/$workspaceId/settings/billing'
    | '/$workspaceId/settings/general'
    | '/$workspaceId/settings/members'
    | '/$workspaceId/settings/notifications'
    | '/$workspaceId/settings/security'
    | '/$workspaceId/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/agents'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/usage'
    | '/_app/$workspaceId'
    | '/_app/$workspaceId/agents'
    | '/_app/$workspaceId/dashboard'
    | '/_app/$workspaceId/settings'
    | '/_app/$workspaceId/tasks'
    | '/_app/$workspaceId/usage'
    | '/_app/$workspaceId/agents/create'
    | '/_app/$workspaceId/settings/billing'
    | '/_app/$workspaceId/settings/general'
    | '/_app/$workspaceId/settings/members'
    | '/_app/$workspaceId/settings/notifications'
    | '/_app/$workspaceId/settings/security'
    | '/_app/$workspaceId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UsageRoute: typeof UsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$workspaceId': {
      id: '/_app/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$workspaceId/usage': {
      id: '/_app/$workspaceId/usage'
      path: '/usage'
      fullPath: '/$workspaceId/usage'
      preLoaderRoute: typeof AppWorkspaceIdUsageRouteImport
      parentRoute: typeof AppWorkspaceIdRoute
    }
    '/_app/$workspaceId/tasks': {
      id: '/_app/$workspaceId/tasks'
      path: '/tasks'
      fullPath: '/$workspaceId/tasks'
      preLoaderRoute: typeof AppWorkspaceIdTasksRouteImport
      parentRoute: typeof AppWorkspaceIdRoute
    }
    '/_app/$workspaceId/settings': {
      id: '/_app/$workspaceId/settings'
      path: '/settings'
      fullPath: '/$workspaceId/settings'
      preLoaderRoute: typeof AppWorkspaceIdSettingsRouteImport
      parentRoute: typeof AppWorkspaceIdRoute
    }
    '/_app/$workspaceId/dashboard': {
      id: '/_app/$workspaceId/dashboard'
      path: '/dashboard'
      fullPath: '/$workspaceId/dashboard'
      preLoaderRoute: typeof AppWorkspaceIdDashboardRouteImport
      parentRoute: typeof AppWorkspaceIdRoute
    }
    '/_app/$workspaceId/agents': {
      id: '/_app/$workspaceId/agents'
      path: '/agents'
      fullPath: '/$workspaceId/agents'
      preLoaderRoute: typeof AppWorkspaceIdAgentsRouteImport
      parentRoute: typeof AppWorkspaceIdRoute
    }
    '/_app/$workspaceId/settings/': {
      id: '/_app/$workspaceId/settings/'
      path: '/'
      fullPath: '/$workspaceId/settings/'
      preLoaderRoute: typeof AppWorkspaceIdSettingsIndexRouteImport
      parentRoute: typeof AppWorkspaceIdSettingsRoute
    }
    '/_app/$workspaceId/settings/security': {
      id: '/_app/$workspaceId/settings/security'
      path: '/security'
      fullPath: '/$workspaceId/settings/security'
      preLoaderRoute: typeof AppWorkspaceIdSettingsSecurityRouteImport
      parentRoute: typeof AppWorkspaceIdSettingsRoute
    }
    '/_app/$workspaceId/settings/notifications': {
      id: '/_app/$workspaceId/settings/notifications'
      path: '/notifications'
      fullPath: '/$workspaceId/settings/notifications'
      preLoaderRoute: typeof AppWorkspaceIdSettingsNotificationsRouteImport
      parentRoute: typeof AppWorkspaceIdSettingsRoute
    }
    '/_app/$workspaceId/settings/members': {
      id: '/_app/$workspaceId/settings/members'
      path: '/members'
      fullPath: '/$workspaceId/settings/members'
      preLoaderRoute: typeof AppWorkspaceIdSettingsMembersRouteImport
      parentRoute: typeof AppWorkspaceIdSettingsRoute
    }
    '/_app/$workspaceId/settings/general': {
      id: '/_app/$workspaceId/settings/general'
      path: '/general'
      fullPath: '/$workspaceId/settings/general'
      preLoaderRoute: typeof AppWorkspaceIdSettingsGeneralRouteImport
      parentRoute: typeof AppWorkspaceIdSettingsRoute
    }
    '/_app/$workspaceId/settings/billing': {
      id: '/_app/$workspaceId/settings/billing'
      path: '/billing'
      fullPath: '/$workspaceId/settings/billing'
      preLoaderRoute: typeof AppWorkspaceIdSettingsBillingRouteImport
      parentRoute: typeof AppWorkspaceIdSettingsRoute
    }
    '/_app/$workspaceId/agents/create': {
      id: '/_app/$workspaceId/agents/create'
      path: '/create'
      fullPath: '/$workspaceId/agents/create'
      preLoaderRoute: typeof AppWorkspaceIdAgentsCreateRouteImport
      parentRoute: typeof AppWorkspaceIdAgentsRoute
    }
  }
}

interface AppWorkspaceIdAgentsRouteChildren {
  AppWorkspaceIdAgentsCreateRoute: typeof AppWorkspaceIdAgentsCreateRoute
}

const AppWorkspaceIdAgentsRouteChildren: AppWorkspaceIdAgentsRouteChildren = {
  AppWorkspaceIdAgentsCreateRoute: AppWorkspaceIdAgentsCreateRoute,
}

const AppWorkspaceIdAgentsRouteWithChildren =
  AppWorkspaceIdAgentsRoute._addFileChildren(AppWorkspaceIdAgentsRouteChildren)

interface AppWorkspaceIdSettingsRouteChildren {
  AppWorkspaceIdSettingsBillingRoute: typeof AppWorkspaceIdSettingsBillingRoute
  AppWorkspaceIdSettingsGeneralRoute: typeof AppWorkspaceIdSettingsGeneralRoute
  AppWorkspaceIdSettingsMembersRoute: typeof AppWorkspaceIdSettingsMembersRoute
  AppWorkspaceIdSettingsNotificationsRoute: typeof AppWorkspaceIdSettingsNotificationsRoute
  AppWorkspaceIdSettingsSecurityRoute: typeof AppWorkspaceIdSettingsSecurityRoute
  AppWorkspaceIdSettingsIndexRoute: typeof AppWorkspaceIdSettingsIndexRoute
}

const AppWorkspaceIdSettingsRouteChildren: AppWorkspaceIdSettingsRouteChildren =
  {
    AppWorkspaceIdSettingsBillingRoute: AppWorkspaceIdSettingsBillingRoute,
    AppWorkspaceIdSettingsGeneralRoute: AppWorkspaceIdSettingsGeneralRoute,
    AppWorkspaceIdSettingsMembersRoute: AppWorkspaceIdSettingsMembersRoute,
    AppWorkspaceIdSettingsNotificationsRoute:
      AppWorkspaceIdSettingsNotificationsRoute,
    AppWorkspaceIdSettingsSecurityRoute: AppWorkspaceIdSettingsSecurityRoute,
    AppWorkspaceIdSettingsIndexRoute: AppWorkspaceIdSettingsIndexRoute,
  }

const AppWorkspaceIdSettingsRouteWithChildren =
  AppWorkspaceIdSettingsRoute._addFileChildren(
    AppWorkspaceIdSettingsRouteChildren,
  )

interface AppWorkspaceIdRouteChildren {
  AppWorkspaceIdAgentsRoute: typeof AppWorkspaceIdAgentsRouteWithChildren
  AppWorkspaceIdDashboardRoute: typeof AppWorkspaceIdDashboardRoute
  AppWorkspaceIdSettingsRoute: typeof AppWorkspaceIdSettingsRouteWithChildren
  AppWorkspaceIdTasksRoute: typeof AppWorkspaceIdTasksRoute
  AppWorkspaceIdUsageRoute: typeof AppWorkspaceIdUsageRoute
}

const AppWorkspaceIdRouteChildren: AppWorkspaceIdRouteChildren = {
  AppWorkspaceIdAgentsRoute: AppWorkspaceIdAgentsRouteWithChildren,
  AppWorkspaceIdDashboardRoute: AppWorkspaceIdDashboardRoute,
  AppWorkspaceIdSettingsRoute: AppWorkspaceIdSettingsRouteWithChildren,
  AppWorkspaceIdTasksRoute: AppWorkspaceIdTasksRoute,
  AppWorkspaceIdUsageRoute: AppWorkspaceIdUsageRoute,
}

const AppWorkspaceIdRouteWithChildren = AppWorkspaceIdRoute._addFileChildren(
  AppWorkspaceIdRouteChildren,
)

interface AppRouteChildren {
  AppWorkspaceIdRoute: typeof AppWorkspaceIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppWorkspaceIdRoute: AppWorkspaceIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AgentsRoute: AgentsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UsageRoute: UsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
