/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteRouteImport } from './routes/usage/route'
import { Route as SsoCallbackRouteRouteImport } from './routes/sso-callback/route'
import { Route as RegisterRouteRouteImport } from './routes/register/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as DownloadRouteRouteImport } from './routes/download/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AgentsRouteRouteImport } from './routes/agents/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspaceIdRouteRouteImport } from './routes/_app/$workspaceId/route'
import { Route as AppWorkspaceIdUsageRouteImport } from './routes/_app/$workspaceId/usage'
import { Route as AppWorkspaceIdTasksRouteImport } from './routes/_app/$workspaceId/tasks'
import { Route as AppWorkspaceIdDashboardRouteImport } from './routes/_app/$workspaceId/dashboard'
import { Route as AppWorkspaceIdSettingsRouteRouteImport } from './routes/_app/$workspaceId/settings/route'
import { Route as AppWorkspaceIdSettingsIndexRouteImport } from './routes/_app/$workspaceId/settings/index'
import { Route as AppWorkspaceIdAgentsIndexRouteImport } from './routes/_app/$workspaceId/agents/index'
import { Route as AppWorkspaceIdSettingsSecurityRouteImport } from './routes/_app/$workspaceId/settings/security'
import { Route as AppWorkspaceIdSettingsNotificationsRouteImport } from './routes/_app/$workspaceId/settings/notifications'
import { Route as AppWorkspaceIdSettingsMembersRouteImport } from './routes/_app/$workspaceId/settings/members'
import { Route as AppWorkspaceIdSettingsGeneralRouteImport } from './routes/_app/$workspaceId/settings/general'
import { Route as AppWorkspaceIdSettingsBillingRouteImport } from './routes/_app/$workspaceId/settings/billing'
import { Route as AppWorkspaceIdAgentsCreateRouteImport } from './routes/_app/$workspaceId/agents/create'
import { Route as AppWorkspaceIdAgentsAgentIdRouteRouteImport } from './routes/_app/$workspaceId/agents/$agentId/route'
import { Route as AppWorkspaceIdAgentsAgentIdIndexRouteImport } from './routes/_app/$workspaceId/agents/$agentId/index'
import { Route as AppWorkspaceIdAgentsAgentIdSettingsRouteImport } from './routes/_app/$workspaceId/agents/$agentId/settings'
import { Route as AppWorkspaceIdAgentsAgentIdHistoryRouteImport } from './routes/_app/$workspaceId/agents/$agentId/history'
import { Route as AppWorkspaceIdAgentsAgentIdContactsRouteImport } from './routes/_app/$workspaceId/agents/$agentId/contacts'

const UsageRouteRoute = UsageRouteRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRouteRoute = SsoCallbackRouteRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRouteRoute = DownloadRouteRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRouteRoute = AgentsRouteRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceIdRouteRoute = AppWorkspaceIdRouteRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceIdUsageRoute = AppWorkspaceIdUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any)
const AppWorkspaceIdTasksRoute = AppWorkspaceIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any)
const AppWorkspaceIdDashboardRoute = AppWorkspaceIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any)
const AppWorkspaceIdSettingsRouteRoute =
  AppWorkspaceIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceIdRouteRoute,
  } as any)
const AppWorkspaceIdSettingsIndexRoute =
  AppWorkspaceIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceIdSettingsRouteRoute,
  } as any)
const AppWorkspaceIdAgentsIndexRoute =
  AppWorkspaceIdAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AppWorkspaceIdRouteRoute,
  } as any)
const AppWorkspaceIdSettingsSecurityRoute =
  AppWorkspaceIdSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AppWorkspaceIdSettingsRouteRoute,
  } as any)
const AppWorkspaceIdSettingsNotificationsRoute =
  AppWorkspaceIdSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppWorkspaceIdSettingsRouteRoute,
  } as any)
const AppWorkspaceIdSettingsMembersRoute =
  AppWorkspaceIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppWorkspaceIdSettingsRouteRoute,
  } as any)
const AppWorkspaceIdSettingsGeneralRoute =
  AppWorkspaceIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AppWorkspaceIdSettingsRouteRoute,
  } as any)
const AppWorkspaceIdSettingsBillingRoute =
  AppWorkspaceIdSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppWorkspaceIdSettingsRouteRoute,
  } as any)
const AppWorkspaceIdAgentsCreateRoute =
  AppWorkspaceIdAgentsCreateRouteImport.update({
    id: '/agents/create',
    path: '/agents/create',
    getParentRoute: () => AppWorkspaceIdRouteRoute,
  } as any)
const AppWorkspaceIdAgentsAgentIdRouteRoute =
  AppWorkspaceIdAgentsAgentIdRouteRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AppWorkspaceIdRouteRoute,
  } as any)
const AppWorkspaceIdAgentsAgentIdIndexRoute =
  AppWorkspaceIdAgentsAgentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceIdAgentsAgentIdRouteRoute,
  } as any)
const AppWorkspaceIdAgentsAgentIdSettingsRoute =
  AppWorkspaceIdAgentsAgentIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceIdAgentsAgentIdRouteRoute,
  } as any)
const AppWorkspaceIdAgentsAgentIdHistoryRoute =
  AppWorkspaceIdAgentsAgentIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AppWorkspaceIdAgentsAgentIdRouteRoute,
  } as any)
const AppWorkspaceIdAgentsAgentIdContactsRoute =
  AppWorkspaceIdAgentsAgentIdContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AppWorkspaceIdAgentsAgentIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/download': typeof DownloadRouteRoute
  '/login': typeof LoginRouteRoute
  '/register': typeof RegisterRouteRoute
  '/sso-callback': typeof SsoCallbackRouteRoute
  '/usage': typeof UsageRouteRoute
  '/$workspaceId': typeof AppWorkspaceIdRouteRouteWithChildren
  '/$workspaceId/settings': typeof AppWorkspaceIdSettingsRouteRouteWithChildren
  '/$workspaceId/dashboard': typeof AppWorkspaceIdDashboardRoute
  '/$workspaceId/tasks': typeof AppWorkspaceIdTasksRoute
  '/$workspaceId/usage': typeof AppWorkspaceIdUsageRoute
  '/$workspaceId/agents/$agentId': typeof AppWorkspaceIdAgentsAgentIdRouteRouteWithChildren
  '/$workspaceId/agents/create': typeof AppWorkspaceIdAgentsCreateRoute
  '/$workspaceId/settings/billing': typeof AppWorkspaceIdSettingsBillingRoute
  '/$workspaceId/settings/general': typeof AppWorkspaceIdSettingsGeneralRoute
  '/$workspaceId/settings/members': typeof AppWorkspaceIdSettingsMembersRoute
  '/$workspaceId/settings/notifications': typeof AppWorkspaceIdSettingsNotificationsRoute
  '/$workspaceId/settings/security': typeof AppWorkspaceIdSettingsSecurityRoute
  '/$workspaceId/agents': typeof AppWorkspaceIdAgentsIndexRoute
  '/$workspaceId/settings/': typeof AppWorkspaceIdSettingsIndexRoute
  '/$workspaceId/agents/$agentId/contacts': typeof AppWorkspaceIdAgentsAgentIdContactsRoute
  '/$workspaceId/agents/$agentId/history': typeof AppWorkspaceIdAgentsAgentIdHistoryRoute
  '/$workspaceId/agents/$agentId/settings': typeof AppWorkspaceIdAgentsAgentIdSettingsRoute
  '/$workspaceId/agents/$agentId/': typeof AppWorkspaceIdAgentsAgentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/download': typeof DownloadRouteRoute
  '/login': typeof LoginRouteRoute
  '/register': typeof RegisterRouteRoute
  '/sso-callback': typeof SsoCallbackRouteRoute
  '/usage': typeof UsageRouteRoute
  '/$workspaceId': typeof AppWorkspaceIdRouteRouteWithChildren
  '/$workspaceId/dashboard': typeof AppWorkspaceIdDashboardRoute
  '/$workspaceId/tasks': typeof AppWorkspaceIdTasksRoute
  '/$workspaceId/usage': typeof AppWorkspaceIdUsageRoute
  '/$workspaceId/agents/create': typeof AppWorkspaceIdAgentsCreateRoute
  '/$workspaceId/settings/billing': typeof AppWorkspaceIdSettingsBillingRoute
  '/$workspaceId/settings/general': typeof AppWorkspaceIdSettingsGeneralRoute
  '/$workspaceId/settings/members': typeof AppWorkspaceIdSettingsMembersRoute
  '/$workspaceId/settings/notifications': typeof AppWorkspaceIdSettingsNotificationsRoute
  '/$workspaceId/settings/security': typeof AppWorkspaceIdSettingsSecurityRoute
  '/$workspaceId/agents': typeof AppWorkspaceIdAgentsIndexRoute
  '/$workspaceId/settings': typeof AppWorkspaceIdSettingsIndexRoute
  '/$workspaceId/agents/$agentId/contacts': typeof AppWorkspaceIdAgentsAgentIdContactsRoute
  '/$workspaceId/agents/$agentId/history': typeof AppWorkspaceIdAgentsAgentIdHistoryRoute
  '/$workspaceId/agents/$agentId/settings': typeof AppWorkspaceIdAgentsAgentIdSettingsRoute
  '/$workspaceId/agents/$agentId': typeof AppWorkspaceIdAgentsAgentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/agents': typeof AgentsRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/download': typeof DownloadRouteRoute
  '/login': typeof LoginRouteRoute
  '/register': typeof RegisterRouteRoute
  '/sso-callback': typeof SsoCallbackRouteRoute
  '/usage': typeof UsageRouteRoute
  '/_app/$workspaceId': typeof AppWorkspaceIdRouteRouteWithChildren
  '/_app/$workspaceId/settings': typeof AppWorkspaceIdSettingsRouteRouteWithChildren
  '/_app/$workspaceId/dashboard': typeof AppWorkspaceIdDashboardRoute
  '/_app/$workspaceId/tasks': typeof AppWorkspaceIdTasksRoute
  '/_app/$workspaceId/usage': typeof AppWorkspaceIdUsageRoute
  '/_app/$workspaceId/agents/$agentId': typeof AppWorkspaceIdAgentsAgentIdRouteRouteWithChildren
  '/_app/$workspaceId/agents/create': typeof AppWorkspaceIdAgentsCreateRoute
  '/_app/$workspaceId/settings/billing': typeof AppWorkspaceIdSettingsBillingRoute
  '/_app/$workspaceId/settings/general': typeof AppWorkspaceIdSettingsGeneralRoute
  '/_app/$workspaceId/settings/members': typeof AppWorkspaceIdSettingsMembersRoute
  '/_app/$workspaceId/settings/notifications': typeof AppWorkspaceIdSettingsNotificationsRoute
  '/_app/$workspaceId/settings/security': typeof AppWorkspaceIdSettingsSecurityRoute
  '/_app/$workspaceId/agents/': typeof AppWorkspaceIdAgentsIndexRoute
  '/_app/$workspaceId/settings/': typeof AppWorkspaceIdSettingsIndexRoute
  '/_app/$workspaceId/agents/$agentId/contacts': typeof AppWorkspaceIdAgentsAgentIdContactsRoute
  '/_app/$workspaceId/agents/$agentId/history': typeof AppWorkspaceIdAgentsAgentIdHistoryRoute
  '/_app/$workspaceId/agents/$agentId/settings': typeof AppWorkspaceIdAgentsAgentIdSettingsRoute
  '/_app/$workspaceId/agents/$agentId/': typeof AppWorkspaceIdAgentsAgentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/dashboard'
    | '/download'
    | '/login'
    | '/register'
    | '/sso-callback'
    | '/usage'
    | '/$workspaceId'
    | '/$workspaceId/settings'
    | '/$workspaceId/dashboard'
    | '/$workspaceId/tasks'
    | '/$workspaceId/usage'
    | '/$workspaceId/agents/$agentId'
    | '/$workspaceId/agents/create'
    | '/$workspaceId/settings/billing'
    | '/$workspaceId/settings/general'
    | '/$workspaceId/settings/members'
    | '/$workspaceId/settings/notifications'
    | '/$workspaceId/settings/security'
    | '/$workspaceId/agents'
    | '/$workspaceId/settings/'
    | '/$workspaceId/agents/$agentId/contacts'
    | '/$workspaceId/agents/$agentId/history'
    | '/$workspaceId/agents/$agentId/settings'
    | '/$workspaceId/agents/$agentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/dashboard'
    | '/download'
    | '/login'
    | '/register'
    | '/sso-callback'
    | '/usage'
    | '/$workspaceId'
    | '/$workspaceId/dashboard'
    | '/$workspaceId/tasks'
    | '/$workspaceId/usage'
    | '/$workspaceId/agents/create'
    | '/$workspaceId/settings/billing'
    | '/$workspaceId/settings/general'
    | '/$workspaceId/settings/members'
    | '/$workspaceId/settings/notifications'
    | '/$workspaceId/settings/security'
    | '/$workspaceId/agents'
    | '/$workspaceId/settings'
    | '/$workspaceId/agents/$agentId/contacts'
    | '/$workspaceId/agents/$agentId/history'
    | '/$workspaceId/agents/$agentId/settings'
    | '/$workspaceId/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/agents'
    | '/dashboard'
    | '/download'
    | '/login'
    | '/register'
    | '/sso-callback'
    | '/usage'
    | '/_app/$workspaceId'
    | '/_app/$workspaceId/settings'
    | '/_app/$workspaceId/dashboard'
    | '/_app/$workspaceId/tasks'
    | '/_app/$workspaceId/usage'
    | '/_app/$workspaceId/agents/$agentId'
    | '/_app/$workspaceId/agents/create'
    | '/_app/$workspaceId/settings/billing'
    | '/_app/$workspaceId/settings/general'
    | '/_app/$workspaceId/settings/members'
    | '/_app/$workspaceId/settings/notifications'
    | '/_app/$workspaceId/settings/security'
    | '/_app/$workspaceId/agents/'
    | '/_app/$workspaceId/settings/'
    | '/_app/$workspaceId/agents/$agentId/contacts'
    | '/_app/$workspaceId/agents/$agentId/history'
    | '/_app/$workspaceId/agents/$agentId/settings'
    | '/_app/$workspaceId/agents/$agentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AgentsRouteRoute: typeof AgentsRouteRoute
  DashboardRouteRoute: typeof DashboardRouteRoute
  DownloadRouteRoute: typeof DownloadRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  RegisterRouteRoute: typeof RegisterRouteRoute
  SsoCallbackRouteRoute: typeof SsoCallbackRouteRoute
  UsageRouteRoute: typeof UsageRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$workspaceId': {
      id: '/_app/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$workspaceId/usage': {
      id: '/_app/$workspaceId/usage'
      path: '/usage'
      fullPath: '/$workspaceId/usage'
      preLoaderRoute: typeof AppWorkspaceIdUsageRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
    '/_app/$workspaceId/tasks': {
      id: '/_app/$workspaceId/tasks'
      path: '/tasks'
      fullPath: '/$workspaceId/tasks'
      preLoaderRoute: typeof AppWorkspaceIdTasksRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
    '/_app/$workspaceId/dashboard': {
      id: '/_app/$workspaceId/dashboard'
      path: '/dashboard'
      fullPath: '/$workspaceId/dashboard'
      preLoaderRoute: typeof AppWorkspaceIdDashboardRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
    '/_app/$workspaceId/settings': {
      id: '/_app/$workspaceId/settings'
      path: '/settings'
      fullPath: '/$workspaceId/settings'
      preLoaderRoute: typeof AppWorkspaceIdSettingsRouteRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
    '/_app/$workspaceId/settings/': {
      id: '/_app/$workspaceId/settings/'
      path: '/'
      fullPath: '/$workspaceId/settings/'
      preLoaderRoute: typeof AppWorkspaceIdSettingsIndexRouteImport
      parentRoute: typeof AppWorkspaceIdSettingsRouteRoute
    }
    '/_app/$workspaceId/agents/': {
      id: '/_app/$workspaceId/agents/'
      path: '/agents'
      fullPath: '/$workspaceId/agents'
      preLoaderRoute: typeof AppWorkspaceIdAgentsIndexRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
    '/_app/$workspaceId/settings/security': {
      id: '/_app/$workspaceId/settings/security'
      path: '/security'
      fullPath: '/$workspaceId/settings/security'
      preLoaderRoute: typeof AppWorkspaceIdSettingsSecurityRouteImport
      parentRoute: typeof AppWorkspaceIdSettingsRouteRoute
    }
    '/_app/$workspaceId/settings/notifications': {
      id: '/_app/$workspaceId/settings/notifications'
      path: '/notifications'
      fullPath: '/$workspaceId/settings/notifications'
      preLoaderRoute: typeof AppWorkspaceIdSettingsNotificationsRouteImport
      parentRoute: typeof AppWorkspaceIdSettingsRouteRoute
    }
    '/_app/$workspaceId/settings/members': {
      id: '/_app/$workspaceId/settings/members'
      path: '/members'
      fullPath: '/$workspaceId/settings/members'
      preLoaderRoute: typeof AppWorkspaceIdSettingsMembersRouteImport
      parentRoute: typeof AppWorkspaceIdSettingsRouteRoute
    }
    '/_app/$workspaceId/settings/general': {
      id: '/_app/$workspaceId/settings/general'
      path: '/general'
      fullPath: '/$workspaceId/settings/general'
      preLoaderRoute: typeof AppWorkspaceIdSettingsGeneralRouteImport
      parentRoute: typeof AppWorkspaceIdSettingsRouteRoute
    }
    '/_app/$workspaceId/settings/billing': {
      id: '/_app/$workspaceId/settings/billing'
      path: '/billing'
      fullPath: '/$workspaceId/settings/billing'
      preLoaderRoute: typeof AppWorkspaceIdSettingsBillingRouteImport
      parentRoute: typeof AppWorkspaceIdSettingsRouteRoute
    }
    '/_app/$workspaceId/agents/create': {
      id: '/_app/$workspaceId/agents/create'
      path: '/agents/create'
      fullPath: '/$workspaceId/agents/create'
      preLoaderRoute: typeof AppWorkspaceIdAgentsCreateRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
    '/_app/$workspaceId/agents/$agentId': {
      id: '/_app/$workspaceId/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/$workspaceId/agents/$agentId'
      preLoaderRoute: typeof AppWorkspaceIdAgentsAgentIdRouteRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
    '/_app/$workspaceId/agents/$agentId/': {
      id: '/_app/$workspaceId/agents/$agentId/'
      path: '/'
      fullPath: '/$workspaceId/agents/$agentId/'
      preLoaderRoute: typeof AppWorkspaceIdAgentsAgentIdIndexRouteImport
      parentRoute: typeof AppWorkspaceIdAgentsAgentIdRouteRoute
    }
    '/_app/$workspaceId/agents/$agentId/settings': {
      id: '/_app/$workspaceId/agents/$agentId/settings'
      path: '/settings'
      fullPath: '/$workspaceId/agents/$agentId/settings'
      preLoaderRoute: typeof AppWorkspaceIdAgentsAgentIdSettingsRouteImport
      parentRoute: typeof AppWorkspaceIdAgentsAgentIdRouteRoute
    }
    '/_app/$workspaceId/agents/$agentId/history': {
      id: '/_app/$workspaceId/agents/$agentId/history'
      path: '/history'
      fullPath: '/$workspaceId/agents/$agentId/history'
      preLoaderRoute: typeof AppWorkspaceIdAgentsAgentIdHistoryRouteImport
      parentRoute: typeof AppWorkspaceIdAgentsAgentIdRouteRoute
    }
    '/_app/$workspaceId/agents/$agentId/contacts': {
      id: '/_app/$workspaceId/agents/$agentId/contacts'
      path: '/contacts'
      fullPath: '/$workspaceId/agents/$agentId/contacts'
      preLoaderRoute: typeof AppWorkspaceIdAgentsAgentIdContactsRouteImport
      parentRoute: typeof AppWorkspaceIdAgentsAgentIdRouteRoute
    }
  }
}

interface AppWorkspaceIdSettingsRouteRouteChildren {
  AppWorkspaceIdSettingsBillingRoute: typeof AppWorkspaceIdSettingsBillingRoute
  AppWorkspaceIdSettingsGeneralRoute: typeof AppWorkspaceIdSettingsGeneralRoute
  AppWorkspaceIdSettingsMembersRoute: typeof AppWorkspaceIdSettingsMembersRoute
  AppWorkspaceIdSettingsNotificationsRoute: typeof AppWorkspaceIdSettingsNotificationsRoute
  AppWorkspaceIdSettingsSecurityRoute: typeof AppWorkspaceIdSettingsSecurityRoute
  AppWorkspaceIdSettingsIndexRoute: typeof AppWorkspaceIdSettingsIndexRoute
}

const AppWorkspaceIdSettingsRouteRouteChildren: AppWorkspaceIdSettingsRouteRouteChildren =
  {
    AppWorkspaceIdSettingsBillingRoute: AppWorkspaceIdSettingsBillingRoute,
    AppWorkspaceIdSettingsGeneralRoute: AppWorkspaceIdSettingsGeneralRoute,
    AppWorkspaceIdSettingsMembersRoute: AppWorkspaceIdSettingsMembersRoute,
    AppWorkspaceIdSettingsNotificationsRoute:
      AppWorkspaceIdSettingsNotificationsRoute,
    AppWorkspaceIdSettingsSecurityRoute: AppWorkspaceIdSettingsSecurityRoute,
    AppWorkspaceIdSettingsIndexRoute: AppWorkspaceIdSettingsIndexRoute,
  }

const AppWorkspaceIdSettingsRouteRouteWithChildren =
  AppWorkspaceIdSettingsRouteRoute._addFileChildren(
    AppWorkspaceIdSettingsRouteRouteChildren,
  )

interface AppWorkspaceIdAgentsAgentIdRouteRouteChildren {
  AppWorkspaceIdAgentsAgentIdContactsRoute: typeof AppWorkspaceIdAgentsAgentIdContactsRoute
  AppWorkspaceIdAgentsAgentIdHistoryRoute: typeof AppWorkspaceIdAgentsAgentIdHistoryRoute
  AppWorkspaceIdAgentsAgentIdSettingsRoute: typeof AppWorkspaceIdAgentsAgentIdSettingsRoute
  AppWorkspaceIdAgentsAgentIdIndexRoute: typeof AppWorkspaceIdAgentsAgentIdIndexRoute
}

const AppWorkspaceIdAgentsAgentIdRouteRouteChildren: AppWorkspaceIdAgentsAgentIdRouteRouteChildren =
  {
    AppWorkspaceIdAgentsAgentIdContactsRoute:
      AppWorkspaceIdAgentsAgentIdContactsRoute,
    AppWorkspaceIdAgentsAgentIdHistoryRoute:
      AppWorkspaceIdAgentsAgentIdHistoryRoute,
    AppWorkspaceIdAgentsAgentIdSettingsRoute:
      AppWorkspaceIdAgentsAgentIdSettingsRoute,
    AppWorkspaceIdAgentsAgentIdIndexRoute:
      AppWorkspaceIdAgentsAgentIdIndexRoute,
  }

const AppWorkspaceIdAgentsAgentIdRouteRouteWithChildren =
  AppWorkspaceIdAgentsAgentIdRouteRoute._addFileChildren(
    AppWorkspaceIdAgentsAgentIdRouteRouteChildren,
  )

interface AppWorkspaceIdRouteRouteChildren {
  AppWorkspaceIdSettingsRouteRoute: typeof AppWorkspaceIdSettingsRouteRouteWithChildren
  AppWorkspaceIdDashboardRoute: typeof AppWorkspaceIdDashboardRoute
  AppWorkspaceIdTasksRoute: typeof AppWorkspaceIdTasksRoute
  AppWorkspaceIdUsageRoute: typeof AppWorkspaceIdUsageRoute
  AppWorkspaceIdAgentsAgentIdRouteRoute: typeof AppWorkspaceIdAgentsAgentIdRouteRouteWithChildren
  AppWorkspaceIdAgentsCreateRoute: typeof AppWorkspaceIdAgentsCreateRoute
  AppWorkspaceIdAgentsIndexRoute: typeof AppWorkspaceIdAgentsIndexRoute
}

const AppWorkspaceIdRouteRouteChildren: AppWorkspaceIdRouteRouteChildren = {
  AppWorkspaceIdSettingsRouteRoute:
    AppWorkspaceIdSettingsRouteRouteWithChildren,
  AppWorkspaceIdDashboardRoute: AppWorkspaceIdDashboardRoute,
  AppWorkspaceIdTasksRoute: AppWorkspaceIdTasksRoute,
  AppWorkspaceIdUsageRoute: AppWorkspaceIdUsageRoute,
  AppWorkspaceIdAgentsAgentIdRouteRoute:
    AppWorkspaceIdAgentsAgentIdRouteRouteWithChildren,
  AppWorkspaceIdAgentsCreateRoute: AppWorkspaceIdAgentsCreateRoute,
  AppWorkspaceIdAgentsIndexRoute: AppWorkspaceIdAgentsIndexRoute,
}

const AppWorkspaceIdRouteRouteWithChildren =
  AppWorkspaceIdRouteRoute._addFileChildren(AppWorkspaceIdRouteRouteChildren)

interface AppRouteRouteChildren {
  AppWorkspaceIdRouteRoute: typeof AppWorkspaceIdRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWorkspaceIdRouteRoute: AppWorkspaceIdRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AgentsRouteRoute: AgentsRouteRoute,
  DashboardRouteRoute: DashboardRouteRoute,
  DownloadRouteRoute: DownloadRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  RegisterRouteRoute: RegisterRouteRoute,
  SsoCallbackRouteRoute: SsoCallbackRouteRoute,
  UsageRouteRoute: UsageRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
